version: '3.8'

services:
  medical-ai-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=your-secure-api-key-here
      - REQUIRE_API_KEY=false
      - HUGGINGFACE_SPACE=Abdhack/medgemma-4b-it
      - HF_TOKEN=${HF_TOKEN}
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s